name: Auto approve and merge

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Add approved label if LGTM
        if: github.actor == 'amw007' && contains(github.event.comment.body, 'LGTM')
        uses: actions/github-script@v6
        with:
          script: |
            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['approved']
            })

  auto-merge:
    needs: auto-approve
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge PR if approved
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            if (pr.data.labels.some(label => label.name === 'approved')) {
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.data.number,
                merge_method: 'squash'
              });
            }
